# Control Data



we should import `torch`.pls note that although we used `pytorh`，we still need import `torch` instead of `pytorch`

In [7]:
import torch

tensor represents an array of numeric values, tensor may have multiple dimensions

In [8]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

We can get the shape of the tensor and the total number of elements in the tensor through `tensor.shape`

In [9]:
x.shape

torch.Size([12])

In [10]:
x.numel()

12

To change the shape of a tensor without changing the number and value of elements, we can call 'tensor.reshape'.

In [11]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Use constants or numbers randomly sampled from a specific distribution initialize tensor 

In [12]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [14]:
torch.randn(3, 4)

tensor([[ 0.3734,  0.9256,  0.2532,  0.3560],
        [ 1.3663,  1.9475,  0.3518, -0.0486],
        [ 1.7704,  0.1921,  1.7889, -0.2951]])

Assign certain value to each element in the required tensor by providing a python list (or nested list)

In [15]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

Common operators (`+`, `-`, `*`, `/`, and `* *`) can be upgraded to element by element operation

In [16]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x**y  

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

Apply more calculations element by element

In [17]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

Concat multiple tensors together

In [18]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

Constructing binary tensor by logical operator

In [19]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

Summation of all elements in a tensor results a tensor with only one element.

In [20]:
X.sum()

tensor(66.)

Even if the shapes are different, we can still perform element by element operations by broadcasting mechanism

In [21]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [22]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

Use `[- 1]` to select the last element, and `[1:3]` to select the second and third elements

In [23]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In addition to reading, we can also write elements to the matrix by specifying the index.

In [24]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

To assign the same value to multiple elements, only need to index all the elements and then assign values to them.

In [25]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

Some operations may cause memory to be allocated for new results

In [26]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [27]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 2005715984704
id(Z): 2005715984704


If tensor is not used repeatedly in subsequent calculation, we can also use `X[:] = X + Y` or `X + = Y` to reduce the memory cost of the operation.

In [28]:
before = id(X)
X += Y
id(X) == before

True

Convert to numpy tensor

In [29]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

Converting a tensor of size 1 to a python scalar

In [30]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)